### PR TITLE
Add Red Line

### PR DESCRIPTION
**Pull request by AlecRosenbaum**
* add the red line, and the combined red/green line files
* removed some debug statements
* somewhat related, I put the excel file I've been using to keep track of the different track attributes into the software engineering google drive folder. It may be more helpful in terms of reading the track. I've also uploaded a clearer + updated picture of the annotated track I have to google drive.

### CODE REVIEW

**Comment by mwm29** [comment]
So the jar fails on init because I needed to hardcode the blocks leaving/entering the yard. I fixed that, but now the wayside fails when the CTC asks occupancy about the red line. Should I push my changes to track_model to be included with this pull request?

**Comment by AlecRosenbaum** [comment]
No don't push to track_model. My thought was that this change should be merged into master as is because it doesn't change our green line functionality or anything else, it just adds the redline csv to the repo. To make things actually work with the red line, we're going to need to implement a lot of changes that are out of the scope of this PR IMO

**Comment by mwm29** [comment]
Makes sense. I'll make a new branch and put my changes there. git stash makes me nervous

**Review by mwm29 — APPROVED** [review]

**Review by iggy14750 — APPROVED** [review]
I Approve!

**Pull request merged**
