### PR TITLE
A Refactor For Me

### PR DESCRIPTION
**Pull request by iggy14750**
Wanted to make a few changes to architecture to accomplish the changes yet to be done.

Sorry for the huge dump of work, but I only now was able to get the change working.

### CODE REVIEW

**Comment by AlecRosenbaum** [comment]
I like it, refactoring is :+1: and code looks cleaner

I do think though that with such a major change we should merge it into staging first, then merge staging into master on Friday after we are able to test thoroughly. That seem reasonable?

**Comment by iggy14750** [comment]
I would like to work off of this for the other features I need to implement.

**Comment by AlecRosenbaum** [comment]
I'll do some basic testing today then approve

**Comment by iggy14750** [comment]
Thanks. :)

**Review by AlecRosenbaum — APPROVED** [review]
basic testing didn't reveal any major bugs, I'm fine with merging

**Pull request merged**
